### ISSUE TITLE
Refine visibility and discoverability of geo works

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/plum#1102]
All geo work objects should be discoverable unless marked otherwise.

**Meaning of visibility for geo works.**

- Public
  - Data is viewable and downloadable
  - `dc_rights_s` field in geoblacklight document is set to 'Public'
  - `dct_references_s` field should contain link to iiif or public wms service
  - `dct_references_s` field should contain link to download data or image
- Campus Only
  - Data is viewable and downloadable only when authenticated with CAS
  - `dc_rights_s` field in geoblacklight document is set to 'Restricted'
  - `dct_references_s` field should contain link to campus-only wms service
  - `dct_references_s` field should contain link to download data or image
- Private
  - Data is NOT viewable or downloadable
  - Metadata is discoverable
  - `dct_references_s` field should contain link to thumbnail image

**Tasks**:
- [x] Create thumbnail derivatives for all geo works.
- [x] Assure that all geo works are discoverable in geoblacklight (Public, Campus-only, Private).
- [x] Make sure that works marked private only pass the thumbnail reference in the geoblacklight document.
- [x] Make a geo work's thumbnail derivative public regardless of the parent work's visibility.
